# Site settings
title: CHCS Family Handbook
email: info@chatthillscharter.org
description: Material Jekyll theme with some enhancements and personal customizations
footer_text: 'Handbook written with <span class="icon-favorite pulse"></span> by the CHCS Board. Inspire children with the natural world.'
baseurl: "" # Url of your website be sure to edit before uploading

# Social usernames
twitter_username: chatthillschsc
github_username:  chatthillscharter

# Admin/Site email


# Google Analytics tracking Code
google_analytics: U-XXXXXX-XA

# Disqus comments shortname
# Site author attribution
# Feel free to edit this. I use admin for myself and guest for a guest blogger if needed
# Theoretically you can have an unlimited number defined.
# In order to get the ID for your gravitar, login to the gravitar website, click My Gravitars
# Click view rating then copy the email hash.
# Be sure to include the appropriate frontmatter in your post to attribute the author


# Build settings
markdown: kramdown
include: ['_pages', '_assets']
exculde: ['.sass_cache', 'README.md']
sass:
  sass_dir: '_assets/_sass'
permalink: "/:title/"

# Defaults
defaults:
  -
    scope:
      path: "_pages"
    values:
      is_in_nav: true
